### ISSUE TITLE
Version 0.2.10 introduced a bug when used with Flask-Admin

### ISSUE THREAD

**Issue by JesseDeLoore** [maarten-dp/flask-restless-datamodel#7]
After trying to run our tests with the new version, we found that we are unable to build the Flask application.
Because the name of the blueprint is passed explicitly we see the following error (instead of the usual warning):
![image](https://user-images.githubusercontent.com/8794713/164198192-8b3af116-79bf-45d8-9279-5fbf71605fc6.png)

I suspect there is a naming conflict with Flask-admin that already registered the `role` blueprint.
From what I can tell this is caused by:
```
datamodel.py:135 self.app.register_blueprint(blueprint, name=collection_name)
datamodel.py:113 collection_name = api_info.collection_name
datamodel.py:55 api_info = data_model.api_manager.created_apis_for[model]
flask_restless/manager.py:646 self.created_apis_for[model] = APIInfo(collection_name, blueprint.name)
flask_restless/manager.py:550-551 
 if collection_name is None:
            collection_name = model.__tablename__ # this get's set to 'role' 
```

We can circumvent the issue by explicitly setting a collection_name with a prefix/suffix on api creation. But I'm not sure that it really solves the issue.

**Comment by maarten-dp** [comment]
I'll try to have a look this evening.

**Comment by maarten-dp** [comment]
Actually, it's a 2 min fix...
I pushed something, could you try installing the master branch and running your tests again?
`pip install git+https://github.com/maarten-dp/flask-restless-datamodel.git`

If this works I'll do a release this evening, if not, let me know what the issue is and I'll continue this evening.

**Comment by JesseDeLoore** [comment]
That seems to work! Thanks a lot.

**Comment by maarten-dp** [comment]
0.2.11 is released :)
